trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script:  dotnet publish --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish --output $(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  displayName: 'Creating web app archive file'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy ARM template files'
  inputs:
    Contents: |
        azuredeploy.parameters.json
        azuredeploy.json
  targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1